/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class monkey_helper_GLJNI */

#ifndef _Included_monkey_helper_GLJNI
#define _Included_monkey_helper_GLJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     monkey_helper_GLJNI
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_monkey_helper_GLJNI_onDrawFrame
  (JNIEnv *, jclass);

/*
 * Class:     monkey_helper_GLJNI
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_monkey_helper_GLJNI_onSurfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     monkey_helper_GLJNI
 * Method:    onSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_monkey_helper_GLJNI_onSurfaceCreated
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     monkey_helper_GLJNI
 * Method:    touchesBegin
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_monkey_helper_GLJNI_touchesBegin
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     monkey_helper_GLJNI
 * Method:    touchesEnd
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_monkey_helper_GLJNI_touchesEnd
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     monkey_helper_GLJNI
 * Method:    touchesMove
 * Signature: ([I[F[F)V
 */
JNIEXPORT void JNICALL Java_monkey_helper_GLJNI_touchesMove
  (JNIEnv *, jclass, jintArray, jfloatArray, jfloatArray);

/*
 * Class:     monkey_helper_GLJNI
 * Method:    touchesCancel
 * Signature: ([I[F[F)V
 */
JNIEXPORT void JNICALL Java_monkey_helper_GLJNI_touchesCancel
  (JNIEnv *, jclass, jintArray, jfloatArray, jfloatArray);

/*
 * Class:     monkey_helper_GLJNI
 * Method:    onPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_monkey_helper_GLJNI_onPause
  (JNIEnv *, jclass);

/*
 * Class:     monkey_helper_GLJNI
 * Method:    onResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_monkey_helper_GLJNI_onResume
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
