/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/asset_manager_jni.h>
/* Header for class monkey_helper_JNIFileUtils */
#include "JNIHelper.h"

#include "core/utils/Log.h"
#include "platform/android/FileUtilsAndroid.h"

#ifndef _Included_monkey_helper_JNIFileUtils
#define _Included_monkey_helper_JNIFileUtils
#ifdef __cplusplus
extern "C" {
#endif

USING_NS_MONKEY

/*
 * Class:     monkey_helper_JNIFileUtils
 * Method:    setApkPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_monkey_helper_JNIFileUtils_setApkPath(JNIEnv *env, jclass jc, jstring str) {
	FileUtilsAndroid *fileutils = dynamic_cast<FileUtilsAndroid*>(FileUtils::getInstance());
	fileutils->setAPKPath(JNIHelper::jstring2string(str));
}

/*
 * Class:     monkey_helper_JNIFileUtils
 * Method:    setAssetsManager
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_monkey_helper_JNIFileUtils_setContext(JNIEnv *env, jclass jc, jobject context, jobject assetManager) {
	JNIHelper::setClassLoaderFrom(context);
	FileUtilsAndroid *fileutils = dynamic_cast<FileUtilsAndroid*>(FileUtils::getInstance());
	fileutils->setAssetManager(AAssetManager_fromJava(env, assetManager));
}

#ifdef __cplusplus
}
#endif
#endif
